apiVersion: apps/v1
kind: Deployment
metadata:
  name: organisations-deployment
  labels:
    app: organisations
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: organisations
  template:
    metadata:
      labels:
        app: organisations
    spec:
      containers:
      - name: organisations
        image: docker.io/library/org:local
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: 500m
          requests:
            memory: "64Mi"
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: organisations-service
spec:
  # type: LoadBalancer
  selector:
    app: organisations
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: organisations-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: organisations-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50