package todo

import (
	"context"
	"reflect"
	"testing"

	"github.com/google/uuid"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// Prepares a temporary in-memory database and performs migrations.
func initDB() *gorm.DB {
	db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{})
	if err != nil {
		panic(err)
	}

	if err := db.AutoMigrate(&Todo{}); err != nil {
		panic(err)
	}

	return db
}

func Test_service_Create(t *testing.T) {
	t.Parallel()

	//	Initialize a temporary in-memory database.
	db := initDB()
	defer func() {
		conn, _ := db.DB()
		_ = conn.Close()
	}()

	//	Create migrations.
	if err := db.AutoMigrate(&Todo{}); err != nil {
		t.Fatal(err)
	}

	type fields struct {
		db *gorm.DB
	}
	type args struct {
		ctx     context.Context
		options *CreateOptions
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    *Todo
		wantErr bool
	}{
		{
			name: "Correct Name",
			fields: fields{
				db: db,
			},
			args: args{
				ctx: context.Background(),
				options: &CreateOptions{
					Title: "Test",
				},
			},
			want:    &Todo{Title: "Test"},
			wantErr: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			s := &service{
				db: tt.fields.db,
			}
			got, err := s.Create(tt.args.ctx, tt.args.options)
			if (err != nil) != tt.wantErr {
				t.Errorf("service.Create() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got.Title, tt.want.Title) {
				t.Errorf("service.Create() = %v, want %v", got.Title, tt.want.Title)
			}

			//	Make sure the primary ID was indeed auto-generated by the beforeCreate gorm hook.
			if got.ID == uuid.Nil {
				t.Errorf("service.Create() = %v, want %v", got.ID, "invalid ID (UUID) generated")
			}
		})
	}
}
